### ISSUE TITLE
 SAM FORMAT: header section and read group

### ISSUE THREAD

**Issue by lyd0527** [denizy/cora#1]
Hi Deniz,
The current CORA version didn't support header section (@SQ...) and read group (bwa mem -R) output. Can u add them for better downstream analysis?
Thx.

**Comment by denizy** [comment]
Hi lyd0527,

Thanks for the opening the issue.

@SQ update is done and will appear with the next version update. For the read group, do you want CORA to just copy a user-defined "@RG" line to the header in the output, but also print the read group on each read mapping line, depending on what read group the FASTQ file belongs to?

Since CORA is designed to operate on multiple FASTQ files at once, I believe the read group assignments should also allow independent read groups and sample pool IDs for separate FASTQ files. I think the most efficient way to allow this is to have them setup in the "cora readFileGen" command, where the user can specify the set of read groups and sample pools for each input FASTQ file. Do you think this type fix would address the issue better?

Cheers,
Deniz

**Comment by lyd0527** [comment]
Hi Deniz,

That's a good idea. 
Looking forward to the next version.

Best regards,
Yuanda

**Comment by denizy** [comment]
Both @SQ header lines and user-specified read group information are now supported. Closing issue.
Thanks,
Deniz
